import Head from 'next/head';
import { useState } from 'react';
import Navbar from '../components/Navbar';
import useMediaQuery from '../hooks/useMediaQuery';

export default function Home() {
	const [selectedPage, setSelectedPage] = useState('home');
	const isAboveMediumScreens = useMediaQuery('(min-width: 1068px)');
	return (
		<div>
			<Head>
				<title>Tailwind with Next JS!</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<div className='app bg-deep-blue'>
				<Navbar selectedPage={selectedPage} setSelectedPage={setSelectedPage} />
			</div>
		</div>
	);
}
